In [1]:
import numpy as np

In [71]:
array = np.array([[1,2], [3,4], [5, 6]])

In [72]:
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
array[:, 0::2] #[start: stop : step]

array([[1, 5, 8],
       [3, 5, 8],
       [5, 5, 8]])

In [78]:
sliced = array[0:2, 0:2]

In [79]:
sliced

array([[1, 2],
       [3, 4]])

In [80]:
sliced[0,0] = 10

In [81]:
array

array([[10,  2],
       [ 3,  4],
       [ 5,  6]])

In [82]:
print(sliced.base)

[[10  2]
 [ 3  4]
 [ 5  6]]


In [85]:
import array as pyArray

In [88]:
array = np.array([[1,2], [3,4], [5, 6]])

In [89]:
array = '223'

In [91]:
x = "hello"
x.append("world")

AttributeError: 'str' object has no attribute 'append'