In [1]:
import decimal

import numpy as np

In [71]:
array = np.array([[1,2], [3,4], [5, 6]])

In [72]:
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [67]:
array[:, 0::2] #[start: stop : step]

array([[1, 5, 8],
       [3, 5, 8],
       [5, 5, 8]])

In [78]:
sliced = array[0:2, 0:2]

In [79]:
sliced

array([[1, 2],
       [3, 4]])

In [80]:
sliced[0,0] = 10

In [81]:
array

array([[10,  2],
       [ 3,  4],
       [ 5,  6]])

In [82]:
print(sliced.base)

[[10  2]
 [ 3  4]
 [ 5  6]]


In [112]:
import array as pyArray

In [88]:
array = np.array([[1,2], [3,4], [5, 6]])

In [94]:
array = '223'

In [95]:
array

'223'

In [101]:
import decimal as pyDecimal

In [106]:
dec= pyDecimal.Decimal(2.5)


In [116]:
arr2 = pyArray.array()

TypeError: array() takes at least 1 argument (0 given)

In [120]:
collection = [1,2,3]
for item in collection.copy():
    if item % 2 ==0:
        collection.remove(item)

for e in range(len(collection)):



[1, 3]

In [ ]:
point = (0, 8)
match point:
    case (0, 0):
        print("Origin")
    case (0, y):
        print(f"Y={y}")
    case (x, 0):
        print(f"X={x}")
    case (x, y):
        print(f"X={x}, Y={y}")
    case _:
        raise ValueError("Not a point")

In [5]:
listt =  [1, 3, 4, 5, 5]

listt.index(5)

3

In [7]:
list = [None] * 10

In [8]:
list.append(10)

In [10]:
for x in range(10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [11]:
x

9